trigger:
- main

pool: EMRSTGSERVER

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Use .NET SDK $(dotnetSdkVersion)"
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use latest .NET 8 SDK available

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
